// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
    NEXTJS_ENV: string;
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: string;
    api: Fetcher;
    ASSETS: Fetcher;
}
