#:schema node_modules/wrangler/config-schema.json
name = "www.system.inc" # Update to the name of your Worker
main = ".worker-next/index.mjs"

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

# Minification helps to keep the Worker bundle size down and improve start up time.
minify = true

# Use the new Workers + Assets to host the static frontend files
assets = { directory = ".worker-next/assets", binding = "ASSETS" }

# Custom Domains
routes = [
    { pattern = "system.inc", custom_domain = true }, # Add your domain here
    { pattern = "www.system.inc", custom_domain = true } # Add your domain here
]

# Enable Logs
[observability]
enabled = true

# Enable Cache KV
[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "YOUR_KV_NAMESPACE_ID" # Add your KV namespace ID here
